modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_terrablender_bridge"
version="${file.jarVersion}"
displayName="Connector Extras Terrablender Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Loads TerraBlender Fabric API entrypoints of Fabric mods on Forge.
'''

[[dependencies.connectorextras_terrablender_bridge]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_terrablender_bridge]]
    modId="minecraft"
    type="required"
    versionRange="[26.1,26.2)"
    ordering="NONE"
    side="BOTH"
